# Generated by Django 3.2.4 on 2021-08-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_announcement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='show_games',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.CharField(default='08/20/21', max_length=20),
        ),
    ]
