# Generated by Django 3.2.4 on 2021-08-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210820_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='show_games',
        ),
    ]
