# Generated by Django 3.2.4 on 2021-08-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_history_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='afc_champ',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Buffalo Bills', 'Buffalo Bills'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Carolina Panthers', 'Carolina Panthers'), ('Cincinnati Bengals', 'Cincinnati Bengals'), ('Cleveland Browns', 'Cleveland Browns'), ('Chicago Bears', 'Chicago Bears'), ('Dallas Cowboys', 'Dallas Cowboys'), ('Denver Broncos', 'Denver Broncos'), ('Detroit Lions', 'Detroit Lions'), ('Green Bay Packers', 'Green Bay Packers'), ('Houston Texans', 'Houston Texans'), ('Indianapolis Colts', 'Indianapolis Colts'), ('Kansas City Chiefs', 'Kansas City Chiefs'), ('Los Angeles Chargers', 'Los Angeles Chargers'), ('Los Angeles Rams', 'Los Angeles Rams'), ('Jacksonville Jaguars', 'Jacksonville Jaguars'), ('Miami Dolphins', 'Miami Dolphins'), ('Minnesota Vikings', 'Minnesota Vikings'), ('New England Patriots', 'New England Patriots'), ('New Orleans Saints', 'New Orleans Saints'), ('New York Giants', 'New York Giants'), ('New York Jets', 'New York Jets'), ('Oakland Raiders', 'Oakland Raiders'), ('Philadelphia Eagles', 'Philadelphia Eagles'), ('San Francisco 49ers', 'San Francisco 49ers'), ('Seattle Seahawks', 'Seattle Seahawks'), ('Pittsburgh Steelers', 'Pittsburgh Steelers'), ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers'), ('Tennessee Titans', 'Tennessee Titans'), ('Washington', 'Washington')], default='Arizona Cardinals', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='big_loser',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Buffalo Bills', 'Buffalo Bills'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Carolina Panthers', 'Carolina Panthers'), ('Cincinnati Bengals', 'Cincinnati Bengals'), ('Cleveland Browns', 'Cleveland Browns'), ('Chicago Bears', 'Chicago Bears'), ('Dallas Cowboys', 'Dallas Cowboys'), ('Denver Broncos', 'Denver Broncos'), ('Detroit Lions', 'Detroit Lions'), ('Green Bay Packers', 'Green Bay Packers'), ('Houston Texans', 'Houston Texans'), ('Indianapolis Colts', 'Indianapolis Colts'), ('Kansas City Chiefs', 'Kansas City Chiefs'), ('Los Angeles Chargers', 'Los Angeles Chargers'), ('Los Angeles Rams', 'Los Angeles Rams'), ('Jacksonville Jaguars', 'Jacksonville Jaguars'), ('Miami Dolphins', 'Miami Dolphins'), ('Minnesota Vikings', 'Minnesota Vikings'), ('New England Patriots', 'New England Patriots'), ('New Orleans Saints', 'New Orleans Saints'), ('New York Giants', 'New York Giants'), ('New York Jets', 'New York Jets'), ('Oakland Raiders', 'Oakland Raiders'), ('Philadelphia Eagles', 'Philadelphia Eagles'), ('San Francisco 49ers', 'San Francisco 49ers'), ('Seattle Seahawks', 'Seattle Seahawks'), ('Pittsburgh Steelers', 'Pittsburgh Steelers'), ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers'), ('Tennessee Titans', 'Tennessee Titans'), ('Washington', 'Washington')], default='Arizona Cardinals', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='nfc_champ',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Buffalo Bills', 'Buffalo Bills'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Carolina Panthers', 'Carolina Panthers'), ('Cincinnati Bengals', 'Cincinnati Bengals'), ('Cleveland Browns', 'Cleveland Browns'), ('Chicago Bears', 'Chicago Bears'), ('Dallas Cowboys', 'Dallas Cowboys'), ('Denver Broncos', 'Denver Broncos'), ('Detroit Lions', 'Detroit Lions'), ('Green Bay Packers', 'Green Bay Packers'), ('Houston Texans', 'Houston Texans'), ('Indianapolis Colts', 'Indianapolis Colts'), ('Kansas City Chiefs', 'Kansas City Chiefs'), ('Los Angeles Chargers', 'Los Angeles Chargers'), ('Los Angeles Rams', 'Los Angeles Rams'), ('Jacksonville Jaguars', 'Jacksonville Jaguars'), ('Miami Dolphins', 'Miami Dolphins'), ('Minnesota Vikings', 'Minnesota Vikings'), ('New England Patriots', 'New England Patriots'), ('New Orleans Saints', 'New Orleans Saints'), ('New York Giants', 'New York Giants'), ('New York Jets', 'New York Jets'), ('Oakland Raiders', 'Oakland Raiders'), ('Philadelphia Eagles', 'Philadelphia Eagles'), ('San Francisco 49ers', 'San Francisco 49ers'), ('Seattle Seahawks', 'Seattle Seahawks'), ('Pittsburgh Steelers', 'Pittsburgh Steelers'), ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers'), ('Tennessee Titans', 'Tennessee Titans'), ('Washington', 'Washington')], default='Arizona Cardinals', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='superbowl_winner',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Buffalo Bills', 'Buffalo Bills'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Carolina Panthers', 'Carolina Panthers'), ('Cincinnati Bengals', 'Cincinnati Bengals'), ('Cleveland Browns', 'Cleveland Browns'), ('Chicago Bears', 'Chicago Bears'), ('Dallas Cowboys', 'Dallas Cowboys'), ('Denver Broncos', 'Denver Broncos'), ('Detroit Lions', 'Detroit Lions'), ('Green Bay Packers', 'Green Bay Packers'), ('Houston Texans', 'Houston Texans'), ('Indianapolis Colts', 'Indianapolis Colts'), ('Kansas City Chiefs', 'Kansas City Chiefs'), ('Los Angeles Chargers', 'Los Angeles Chargers'), ('Los Angeles Rams', 'Los Angeles Rams'), ('Jacksonville Jaguars', 'Jacksonville Jaguars'), ('Miami Dolphins', 'Miami Dolphins'), ('Minnesota Vikings', 'Minnesota Vikings'), ('New England Patriots', 'New England Patriots'), ('New Orleans Saints', 'New Orleans Saints'), ('New York Giants', 'New York Giants'), ('New York Jets', 'New York Jets'), ('Oakland Raiders', 'Oakland Raiders'), ('Philadelphia Eagles', 'Philadelphia Eagles'), ('San Francisco 49ers', 'San Francisco 49ers'), ('Seattle Seahawks', 'Seattle Seahawks'), ('Pittsburgh Steelers', 'Pittsburgh Steelers'), ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers'), ('Tennessee Titans', 'Tennessee Titans'), ('Washington', 'Washington')], default='Arizona Cardinals', max_length=20),
        ),
    ]
